name: Deploy CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Building App
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Cache
        uses: actions/cache@v4.0.2
        env:
          cache-name: cache-node-modules
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          path: node_modules

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Construindo Imagem Docker
        run: docker build . -t nodeMax:1.0.0

  deploy:
    name: Subindo para o Docker
    runs-on: ubuntu-latest
    needs: build
    steps:
      
      - name: Checkout
        uses: actions/checkout@main

      - name: Cache
        uses: actions/cache@v4.0.2
        env:
          cache-name: cache-node-modules
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          path: node_modules
